name: Run scheduled jobs

on:
  schedule:
    - cron: '10,25,40,55 * * * *'

jobs:
  make-arbitrary-pr:
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
      - name: Call create-pr workflow
        run: |
          gh workflow run create-pr.yaml --ref "main"
