name: Run scheduled jobs

on:
  schedule:
    - cron: '10,25,40,55 * * * *'
  workflow_dispatch:

jobs:
  make-arbitrary-pr:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      pull-requests: write
      contents: write
      checks: write
      statuses: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Make arbitrary commit and PR
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d-%H-%M")
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b "$TIMESTAMP"
          echo "a random file" > $TIMESTAMP.txt
          git add $TIMESTAMP.txt
          git commit -m "Arbitrary file update at $TIMESTAMP"
          CURRENT_SHA=$(git rev-parse --verify HEAD)
          git push origin "$TIMESTAMP"
          gh pr create \
            --title "$TIMESTAMP - scheduled pr" \
            --body "pr body here" \
            --base "main" \
            --head "$TIMESTAMP"
          gh api -X POST -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -f 'name=echo' \
            -f "head_sha=$CURRENT_SHA" \
            -f "status=in_progress" \
            -f 'output[title]=echo' \
            /repos/alexcottner/actions-sandbox/check-runs

# notes: 
# You must select "Allow GitHub Actions to create and approve pull requests" under Settings > Actions > General
# You must explicitely require checks on PRs before allowing them to be merged under Settings > Branches > Require status checks to pass before merging
