name: Tags experiments

on: 
  workflow_dispatch:

jobs:
  tags:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        with: 
          fetch-depth: 0
        uses: actions/checkout@v4

      - name: do tag stuff
        run: |
            git fetch --tags
            git describe --tags --abbrev=4
